### PR TITLE
SerialIface: remove more branching using function pointer.

### PR DESCRIPTION
**Pull request by ghost**
@vincentbernat May I suggest this change to reduce branching further?

### CODE REVIEW

**Comment by vincentbernat** [comment]
You could even remove one additional branching by setting the initial value to `waitForBufSizeCmd`.

**Comment by ghost** [comment]
True! I'll do it when I get home from work.

**Comment by ghost** [comment]
@vincentbernat Done.

**Comment by vincentbernat** [comment]
:+1:

**Pull request merged**
